print("Loaded sh_config.lua")

SWQ = {}

SWQ.Config = {
    Towns = {
        ["platform"] = {
            Name = 'Construct',
            ShowNameOnEntry = true,
            MinBound = Vector(-878.538330, 812.271667, -12395.636719),
            MaxBound = Vector(872.486572, -891.692871, -11448.763672),
            AmountOfNPCS = 5,
        },
        ["boreas_town"] = {
            Name = 'Boreas',
            ShowNameOnEntry = true,
            MinBound = Vector(-11046.111328, -5864.525879, -10522.444336),
            MaxBound = Vector(-8075.291016, -9054.171875, -9502.372070),
            AmountOfNPCS = 5,
        }
    },

    NPCs = {
        DrawPaths      = true, -- This is only for testing and debugging the nextbots.
        RandomiseColor = true, -- Make them random colors, could be good for SWRP for different species.

        RandomChatter  = {
            male = {
                'vo/coast/odessa/nlo_cub_thatsthat.wav',
                'vo/coast/odessa/nlo_cub_youllmakeit.wav',
                'vo/npc/male01/answer01.wav',
                'vo/npc/male01/answer02.wav',
                'vo/npc/male01/answer03.wav',
                'vo/npc/male01/answer04.wav',
                'vo/npc/male01/answer05.wav',
                'vo/npc/male01/answer07.wav',
                'vo/npc/male01/answer08.wav',
                'vo/npc/male01/answer09.wav',
                'vo/npc/male01/answer10.wav',
                'vo/npc/male01/answer11.wav',
                'vo/npc/male01/answer12.wav',
                'vo/npc/male01/answer13.wav',
                'vo/npc/male01/answer14.wav',
                'vo/npc/male01/answer15.wav',
                'vo/npc/male01/answer16.wav',
                'vo/npc/male01/answer17.wav',
                'vo/npc/male01/answer18.wav',
                'vo/npc/male01/answer19.wav',
                'vo/npc/male01/answer20.wav',
                'vo/npc/male01/answer21.wav',
                'vo/npc/male01/answer22.wav',
                'vo/npc/male01/answer23.wav',
                'vo/npc/male01/answer24.wav',
                'vo/npc/male01/answer25.wav',
                'vo/npc/male01/answer26.wav',
                'vo/npc/male01/answer27.wav',
                'vo/npc/male01/answer28.wav',
                'vo/npc/male01/answer29.wav',
                'vo/npc/male01/answer30.wav',
                'vo/npc/male01/answer31.wav',
                'vo/npc/male01/answer32.wav',
                'vo/npc/male01/answer33.wav',
                'vo/npc/male01/answer34.wav',
                'vo/npc/male01/answer35.wav',
                'vo/npc/male01/answer36.wav',
                'vo/npc/male01/answer37.wav',
                'vo/npc/male01/answer38.wav',
                'vo/npc/male01/answer39.wav',
                'vo/npc/male01/answer40.wav',
                'vo/npc/male01/pardonme01.wav',
                'vo/npc/male01/pardonme02.wav',
                'vo/npc/male01/question01.wav',
                'vo/npc/male01/question02.wav',
                'vo/npc/male01/question03.wav',
                'vo/npc/male01/question04.wav',
                'vo/npc/male01/question05.wav',
                'vo/npc/male01/question06.wav',
                'vo/npc/male01/question07.wav',
                'vo/npc/male01/question08.wav',
                'vo/npc/male01/question09.wav',
                'vo/npc/male01/question10.wav',
                'vo/npc/male01/question11.wav',
                'vo/npc/male01/question12.wav',
                'vo/npc/male01/question13.wav',
                'vo/npc/male01/question14.wav',
                'vo/npc/male01/question15.wav',
                'vo/npc/male01/question16.wav',
                'vo/npc/male01/question17.wav',
                'vo/npc/male01/question18.wav',
                'vo/npc/male01/question19.wav',
                'vo/npc/male01/question20.wav',
                'vo/npc/male01/question21.wav',
                'vo/npc/male01/question22.wav',
                'vo/npc/male01/question23.wav',
                'vo/npc/male01/question25.wav',
                'vo/npc/male01/question26.wav',
                'vo/npc/male01/question27.wav',
                'vo/npc/male01/question28.wav',
                'vo/npc/male01/question29.wav',
                'vo/npc/male01/question30.wav',
                'vo/npc/male01/question31.wav',
                'vo/npc/male01/squad_affirm01.wav',
                'vo/npc/male01/squad_affirm02.wav',
                'vo/npc/male01/squad_affirm03.wav',
                'vo/npc/male01/squad_affirm04.wav',
                'vo/npc/male01/squad_affirm05.wav',
                'vo/npc/male01/squad_affirm06.wav',
                'vo/npc/male01/squad_affirm07.wav',
                'vo/npc/male01/squad_affirm08.wav',
                'vo/npc/male01/squad_affirm09.wav',
                'vo/npc/male01/squad_approach01.wav',
                'vo/npc/male01/squad_approach02.wav',
                'vo/npc/male01/squad_approach03.wav',
                'vo/npc/male01/squad_approach04.wav',
                'vo/npc/male01/squad_away01.wav',
                'vo/npc/male01/squad_away02.wav',
                'vo/npc/male01/squad_away03.wav',
                'vo/npc/male01/squad_follow01.wav',
                'vo/npc/male01/squad_follow02.wav',
                'vo/npc/male01/squad_follow03.wav',
                'vo/npc/male01/squad_follow04.wav',
                'vo/npc/male01/squad_greet01.wav',
                'vo/npc/male01/squad_greet02.wav',
                'vo/npc/male01/squad_greet04.wav',
                'vo/npc/male01/squad_reinforce_group01.wav',
                'vo/npc/male01/squad_reinforce_group02.wav',
                'vo/npc/male01/squad_reinforce_group03.wav',
                'vo/npc/male01/squad_reinforce_group04.wav',
                'vo/npc/male01/squad_reinforce_single01.wav',
                'vo/npc/male01/squad_reinforce_single02.wav',
                'vo/npc/male01/squad_reinforce_single03.wav',
                'vo/npc/male01/squad_reinforce_single04.wav',
                'vo/npc/male01/squad_train01.wav',
                'vo/npc/male01/squad_train02.wav',
                'vo/npc/male01/squad_train03.wav',
                'vo/npc/male01/squad_train04.wav',
                'vo/npc/male01/startle01.wav',
                'vo/npc/male01/startle02.wav',
                'vo/npc/male01/stopitfm.wav',
                'vo/npc/male01/strider.wav',
                'vo/npc/male01/strider_run.wav',
                'vo/npc/male01/takecover02.wav',
                'vo/npc/male01/thehacks01.wav',
                'vo/npc/male01/thehacks02.wav',
                'vo/npc/male01/thislldonicely01.wav',
                'vo/npc/male01/uhoh.wav',
                'vo/npc/male01/upthere01.wav',
                'vo/npc/male01/upthere02.wav',
                'vo/npc/male01/vanswer01.wav',
                'vo/npc/male01/vanswer02.wav',
                'vo/npc/male01/vanswer03.wav',
                'vo/npc/male01/vanswer04.wav',
                'vo/npc/male01/vanswer05.wav',
                'vo/npc/male01/vanswer06.wav',
                'vo/npc/male01/vanswer07.wav',
                'vo/npc/male01/vanswer08.wav',
                'vo/npc/male01/vanswer09.wav',
                'vo/npc/male01/vanswer10.wav',
                'vo/npc/male01/vanswer11.wav',
                'vo/npc/male01/vanswer12.wav',
                'vo/npc/male01/vanswer13.wav',
                'vo/npc/male01/vanswer14.wav',
                'vo/npc/male01/vquestion01.wav',
                'vo/npc/male01/vquestion02.wav',
                'vo/npc/male01/vquestion03.wav',
                'vo/npc/male01/vquestion04.wav',
                'vo/npc/male01/vquestion05.wav',
                'vo/npc/male01/vquestion06.wav',
                'vo/npc/male01/vquestion07.wav',
            },


            female = {

                'vo/coast/barn/female01/lite_rockets03.wav',
                'vo/coast/barn/female01/gettauoff.wav',
                'vo/coast/barn/female01/ditchcar.wav',
                'vo/coast/barn/female01/chatter.wav',
                'vo/canals/female01/gunboat_giveemhell.wav',
                'vo/coast/odessa/female01/nlo_citizen_greet01.wav',
                'vo/coast/odessa/female01/nlo_citizen_greet02.wav',
                'vo/coast/odessa/female01/nlo_citizen_greet03.wav',
                'vo/coast/odessa/female01/nlo_citizen_greet04.wav',
                'vo/coast/odessa/female01/nlo_citizen_post01.wav',
                'vo/coast/odessa/female01/nlo_citizen_post02.wav',
                'vo/coast/odessa/female01/nlo_citizen_post03.wav',
                'vo/coast/odessa/female01/nlo_yourcarsir.wav',
                'vo/npc/female01/abouttime01.wav',
                'vo/npc/female01/abouttime02.wav',
                'vo/npc/female01/answer01.wav',
                'vo/npc/female01/answer02.wav',
                'vo/npc/female01/answer03.wav',
                'vo/npc/female01/answer04.wav',
                'vo/npc/female01/answer05.wav',
                'vo/npc/female01/answer07.wav',
                'vo/npc/female01/answer08.wav',
                'vo/npc/female01/answer09.wav',
                'vo/npc/female01/answer10.wav',
                'vo/npc/female01/answer11.wav',
                'vo/npc/female01/answer12.wav',
                'vo/npc/female01/answer13.wav',
                'vo/npc/female01/answer14.wav',
                'vo/npc/female01/answer15.wav',
                'vo/npc/female01/answer16.wav',
                'vo/npc/female01/answer17.wav',
                'vo/npc/female01/answer18.wav',
                'vo/npc/female01/answer19.wav',
                'vo/npc/female01/answer20.wav',
                'vo/npc/female01/answer21.wav',
                'vo/npc/female01/answer22.wav',
                'vo/npc/female01/answer23.wav',
                'vo/npc/female01/answer24.wav',
                'vo/npc/female01/answer25.wav',
                'vo/npc/female01/answer26.wav',
                'vo/npc/female01/answer27.wav',
                'vo/npc/female01/answer28.wav',
                'vo/npc/female01/answer29.wav',
                'vo/npc/female01/answer30.wav',
                'vo/npc/female01/answer31.wav',
                'vo/npc/female01/answer32.wav',
                'vo/npc/female01/answer33.wav',
                'vo/npc/female01/answer34.wav',
                'vo/npc/female01/answer35.wav',
                'vo/npc/female01/answer36.wav',
                'vo/npc/female01/answer37.wav',
                'vo/npc/female01/answer38.wav',
                'vo/npc/female01/answer39.wav',
                'vo/npc/female01/answer40.wav',
                'vo/npc/female01/pardonme01.wav',
                'vo/npc/female01/pardonme02.wav',
                'vo/npc/female01/question01.wav',
                'vo/npc/female01/question02.wav',
                'vo/npc/female01/question03.wav',
                'vo/npc/female01/question04.wav',
                'vo/npc/female01/question05.wav',
                'vo/npc/female01/question06.wav',
                'vo/npc/female01/question07.wav',
                'vo/npc/female01/question08.wav',
                'vo/npc/female01/question09.wav',
                'vo/npc/female01/question10.wav',
                'vo/npc/female01/question11.wav',
                'vo/npc/female01/question12.wav',
                'vo/npc/female01/question13.wav',
                'vo/npc/female01/question14.wav',
                'vo/npc/female01/question15.wav',
                'vo/npc/female01/question16.wav',
                'vo/npc/female01/question17.wav',
                'vo/npc/female01/question18.wav',
                'vo/npc/female01/question19.wav',
                'vo/npc/female01/question20.wav',
                'vo/npc/female01/question21.wav',
                'vo/npc/female01/question22.wav',
                'vo/npc/female01/question23.wav',
                'vo/npc/female01/question25.wav',
                'vo/npc/female01/question26.wav',
                'vo/npc/female01/question27.wav',
                'vo/npc/female01/question28.wav',
                'vo/npc/female01/question29.wav',
                'vo/npc/female01/question30.wav',
                'vo/npc/female01/question31.wav',
                'vo/npc/female01/squad_affirm01.wav',
                'vo/npc/female01/squad_affirm02.wav',
                'vo/npc/female01/squad_affirm03.wav',
                'vo/npc/female01/squad_affirm04.wav',
                'vo/npc/female01/squad_affirm05.wav',
                'vo/npc/female01/squad_affirm06.wav',
                'vo/npc/female01/squad_affirm07.wav',
                'vo/npc/female01/squad_affirm08.wav',
                'vo/npc/female01/squad_affirm09.wav',
                'vo/npc/female01/squad_approach01.wav',
                'vo/npc/female01/squad_approach02.wav',
                'vo/npc/female01/squad_approach03.wav',
                'vo/npc/female01/squad_approach04.wav',
                'vo/npc/female01/squad_away01.wav',
                'vo/npc/female01/squad_away02.wav',
                'vo/npc/female01/squad_away03.wav',
                'vo/npc/female01/squad_follow01.wav',
                'vo/npc/female01/squad_follow02.wav',
                'vo/npc/female01/squad_follow03.wav',
                'vo/npc/female01/squad_follow04.wav',
                'vo/npc/female01/squad_greet01.wav',
                'vo/npc/female01/squad_greet02.wav',
                'vo/npc/female01/squad_greet04.wav',
                'vo/npc/female01/squad_reinforce_group01.wav',
                'vo/npc/female01/squad_reinforce_group02.wav',
                'vo/npc/female01/squad_reinforce_group03.wav',
                'vo/npc/female01/squad_reinforce_group04.wav',
                'vo/npc/female01/squad_reinforce_single01.wav',
                'vo/npc/female01/squad_reinforce_single02.wav',
                'vo/npc/female01/squad_reinforce_single03.wav',
                'vo/npc/female01/squad_reinforce_single04.wav',
                'vo/npc/female01/squad_train01.wav',
                'vo/npc/female01/squad_train02.wav',
                'vo/npc/female01/squad_train03.wav',
                'vo/npc/female01/squad_train04.wav',
                'vo/npc/female01/startle01.wav',
                'vo/npc/female01/startle02.wav',
                'vo/npc/female01/stopitfm.wav',
                'vo/npc/female01/strider.wav',
                'vo/npc/female01/strider_run.wav',
                'vo/npc/female01/takecover02.wav',
                'vo/npc/female01/thehacks01.wav',
                'vo/npc/female01/thehacks02.wav',
                'vo/npc/female01/thislldonicely01.wav',
                'vo/npc/female01/uhoh.wav',
                'vo/npc/female01/upthere01.wav',
                'vo/npc/female01/upthere02.wav',
                'vo/npc/female01/vanswer01.wav',
                'vo/npc/female01/vanswer02.wav',
                'vo/npc/female01/vanswer03.wav',
                'vo/npc/female01/vanswer04.wav',
                'vo/npc/female01/vanswer05.wav',
                'vo/npc/female01/vanswer06.wav',
                'vo/npc/female01/vanswer07.wav',
                'vo/npc/female01/vanswer08.wav',
                'vo/npc/female01/vanswer09.wav',
                'vo/npc/female01/vanswer10.wav',
                'vo/npc/female01/vanswer11.wav',
                'vo/npc/female01/vanswer12.wav',
                'vo/npc/female01/vanswer13.wav',
                'vo/npc/female01/vanswer14.wav',
                'vo/npc/female01/vquestion01.wav',
                'vo/npc/female01/vquestion02.wav',
                'vo/npc/female01/vquestion03.wav',
                'vo/npc/female01/vquestion04.wav',
                'vo/npc/female01/vquestion05.wav',
                'vo/npc/female01/vquestion06.wav',
                'vo/npc/female01/vquestion07.wav',
            },
        },

        Greeting       = {
            male = {
                'vo/npc/male01/hellodrfm02.wav',
                'vo/npc/male01/hellodrfm01.wav',
                'vo/npc/male01/heretohelp01.wav',
                'vo/npc/male01/heretohelp02.wav',
                'vo/npc/male01/hi01.wav',
                'vo/npc/male01/hi02.wav',
                'vo/npc/male01/illstayhere01.wav',
                'vo/npc/male01/heydoc01.wav',
                'vo/npc/male01/heydoc02.wav',
                'vo/npc/male01/abouttime01.wav',
                'vo/npc/male01/abouttime02.wav',
                'vo/npc/male01/hi01.wav',
                'vo/npc/male01/hi01.wav'
            },

            female = {
                'vo/npc/female01/hellodrfm02.wav',
                'vo/npc/female01/hellodrfm01.wav',
                'vo/npc/female01/heretohelp01.wav',
                'vo/npc/female01/heretohelp02.wav',
                'vo/npc/female01/hi01.wav',
                'vo/npc/female01/hi02.wav',
                'vo/npc/female01/illstayhere01.wav',
                'vo/npc/female01/heydoc01.wav',
                'vo/npc/female01/heydoc02.wav',
                'vo/npc/female01/hi01.wav',
                'vo/npc/female01/hi02.wav'
            }

        },

        FemaleModels   = {
            'models/Humans/Group01/Female_01.mdl',
            'models/Humans/Group01/Female_02.mdl',
            'models/Humans/Group01/Female_03.mdl',
            'models/Humans/Group01/Female_04.mdl',
            'models/Humans/Group01/Female_06.mdl',
            'models/Humans/Group01/Female_07.mdl',
        },

        MaleCivModels  = {
            'models/Humans/Group01/Male_01.mdl',
            'models/Humans/Group01/male_02.mdl',
            'models/Humans/Group01/male_03.mdl',
            'models/Humans/Group01/Male_04.mdl',
            'models/Humans/Group01/male_06.mdl',
            'models/Humans/Group01/male_07.mdl',
            'models/Humans/Group01/male_08.mdl',
            'models/Humans/Group01/male_09.mdl',
        },


        QuestRejection = {
            male = {
                'vo/npc/male01/no01.wav',
                'vo/npc/male01/no02.wav',
                'vo/npc/male01/sorry01.wav',
                'vo/npc/male01/sorry02.wav',
                'vo/npc/male01/sorry03.wav'
            },
            female = {
                'vo/npc/female01/no01.wav',
                'vo/npc/female01/no02.wav',
                'vo/npc/female01/sorry01.wav',
                'vo/npc/female01/sorry02.wav',
                'vo/npc/female01/sorry03.wav'
            }
        },

        -- Fear system, if reputation is too low

        FearSounds = {
            male = {
                'vo/npc/male01/help01.wav',
                'vo/npc/male01/uhoh.wav'
            },
            female = {
                'vo/npc/female01/help01.wav',
                'vo/npc/female01/uhoh.wav'
            }
        },
    },

    Police = {
        PoliceModels = {"models/Police.mdl"},
        PoliceAntagoniseSounds = {},
        PolicePraiseSounds = {

        },
        PoliceInspectionStartSounds = {
          "npc/metropolice/vo/holditrightthere.wav",
          "npc/metropolice/vo/holdit.wav",
        },
        PoliceInspectionEndSounds = {
            "npc/metropolice/vo/movealong.wav",
            "npc/metropolice/vo/movealong3.wav",
            "npc/metropolice/vo/moveit2.wav",
            "npc/metropolice/vo/moveit.wav",
            "npc/metropolice/vo/getoutofhere.wav",
        },
        PoliceChaseSounds = {
            "npc/metropolice/vo/hesrunning.wav",
            "npc/metropolice/vo/help.wav",
        },
        PoliceArrestSounds = {
            "npc/metropolice/vo/11-99officerneedsassistance.wav",
            "npc/metropolice/vo/acquiringonvisual.wav",
            "npc/metropolice/vo/allunitscloseonsuspect.wav",
            "npc/metropolice/vo/backup.wav",
            "npc/metropolice/vo/allunitsrespondcode3.wav",
            "npc/metropolice/vo/allunitsreportlocationsuspect.wav",
            "npc/metropolice/vo/allunitsmovein.wav",
            "npc/metropolice/vo/loyaltycheckfailure.wav",
        }
    }
}

-- Reputation System
-- Do not remove the keys (REASON_KILL_NPC)
SWQ.Reputation = {
    ['REASON_DAMAGE_NPC'] = {
        AmountRemoved = 3,
        Message = "You have lost %s reputation points for hurting an NPC within %s"
    },
    ['REASON_KILL_NPC'] = {
        AmountRemoved = 5,
        Message = "You have lost %s reputation points for killing an NPC within %s"
    },
    ['REASON_DAMAGE_POLICE'] = {
        AmountRemoved = 3,
        Message = "You have lost %s reputation points for hurting police within %s"
    },
    ['REASON_KILL_POLICE'] = {
        AmountRemoved = 10,
        Message = "You have lost %s reputation points for killing police within %s"
    },
}
